// File generated by FlutterFire CLI for project ayskampuss.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return ios;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          're-run flutterfire configure with windows platform if needed.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBndeLh7kUr53XKqS9WvE5P3YMsfrRfLLE',
    appId: '1:378741313538:web:d6941781b364ee6c91971b',
    messagingSenderId: '378741313538',
    projectId: 'ayskampuss',
    authDomain: 'ayskampuss.firebaseapp.com',
    storageBucket: 'ayskampuss.firebasestorage.app',
    measurementId: 'G-LY8L1F561Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXmToBmwKqyBg_-uG-mlis54ZKr4SBf9k',
    appId: '1:378741313538:android:6ab6f0d02297d15191971b',
    messagingSenderId: '378741313538',
    projectId: 'ayskampuss',
    storageBucket: 'ayskampuss.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQPYalWoq21MEAEMPJG5YVwZl6eBtdUk4',
    appId: '1:378741313538:ios:2657fe372f2f2d5491971b',
    messagingSenderId: '378741313538',
    projectId: 'ayskampuss',
    storageBucket: 'ayskampuss.firebasestorage.app',
    iosBundleId: 'com.aystech.mtMobil',
  );
}
